# Generated by Django 5.2.2 on 2025-08-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_produto_pedido_produtonopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
